defaults: &defaults
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    environment:
      MAVEN_OPTS: -Xmx3200m
      _JAVA_OPTIONS: "-Xms1g -Xmx1g"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.2.0:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Build and push to Artifactory
          command: |
            mvn deploy -s .circleci/settings.xml -Dartifactory.username=$ARTIFACTORY_USER -Dartifactory.password=$ARTIFACTORY_APIKEY

workflows:
  version: 2
  ci_build:
    jobs:
      - build:
          context: deploy-keys